name: Build

# Controls when the workflow will run
on: 
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.100'
      
      - name: Build the solution
        run: dotnet build -c Release --output out/

      - name: Prepare Upload
        run: 
          rm -rf out/*.json
          rm -rf out/HttpServer.dll
          echo "TAG_NAME=$(git rev-list --count HEAD)" >> $env:GITHUB_OUTPUT
      - name: Upload Plugin
        uses: actions/upload-artifact@v3
        with:
          name: Plugin
          path: out/*
      
      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          prerelease: true
          tag_name: v${{ steps.setenvo.outputs.TAG_NAME }}
          target_commitish: ${{ github.sha }}
          name: Build
          files: 
            out/*
